import base64
import os
import re

import requests

GITHUB_API = "https://api.github.com"


def github_headers() -> dict[str, str]:
    return {
        "Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def find_open_pr(repo: str, label: str) -> dict | None:
    resp = requests.get(
        f"{GITHUB_API}/repos/{repo}/pulls",
        params={"state": "open", "labels": label},
        headers=github_headers(),
        timeout=15,
    )
    resp.raise_for_status()
    prs = resp.json()
    return prs[0] if prs else None


def get_repo_file(repo: str, ref: str, path: str) -> dict[str, str]:
    resp = requests.get(
        f"{GITHUB_API}/repos/{repo}/contents/{path}",
        params={"ref": ref},
        headers=github_headers(),
        timeout=15,
    )
    resp.raise_for_status()
    body = resp.json()
    return {
        "content": base64.b64decode(body["content"]).decode("utf-8"),
        "sha": body["sha"],
    }


def create_branch(repo: str, base_branch: str, branch: str) -> None:
    base_ref = requests.get(
        f"{GITHUB_API}/repos/{repo}/git/ref/heads/{base_branch}",
        headers=github_headers(),
        timeout=15,
    )
    base_ref.raise_for_status()
    base_sha = base_ref.json()["object"]["sha"]

    resp = requests.post(
        f"{GITHUB_API}/repos/{repo}/git/refs",
        headers=github_headers(),
        json={"ref": f"refs/heads/{branch}", "sha": base_sha},
        timeout=15,
    )
    resp.raise_for_status()


def commit_file(
    repo: str, branch: str, path: str, content: str, sha: str, message: str
) -> None:
    resp = requests.put(
        f"{GITHUB_API}/repos/{repo}/contents/{path}",
        headers=github_headers(),
        json={
            "message": message,
            "content": base64.b64encode(content.encode("utf-8")).decode("ascii"),
            "sha": sha,
            "branch": branch,
        },
        timeout=30,
    )
    resp.raise_for_status()


def create_pull_request(
    repo: str, base_branch: str, branch: str, title: str, body: str
) -> dict:
    resp = requests.post(
        f"{GITHUB_API}/repos/{repo}/pulls",
        headers=github_headers(),
        json={"title": title, "head": branch, "base": base_branch, "body": body},
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()


def ensure_label(repo: str, issue_number: int, label: str) -> None:
    resp = requests.post(
        f"{GITHUB_API}/repos/{repo}/issues/{issue_number}/labels",
        headers=github_headers(),
        json={"labels": [label]},
        timeout=15,
    )
    if resp.status_code != 422:
        resp.raise_for_status()
        return

    requests.post(
        f"{GITHUB_API}/repos/{repo}/labels",
        headers=github_headers(),
        json={"name": label, "color": "0e8a16"},
        timeout=15,
    )
    retry = requests.post(
        f"{GITHUB_API}/repos/{repo}/issues/{issue_number}/labels",
        headers=github_headers(),
        json={"labels": [label]},
        timeout=15,
    )
    retry.raise_for_status()


def build_branch_name(dag_id: str, run_id: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "-", run_id).strip("-")[:24]
    return f"auto-fix/{dag_id}/{slug}"


def render_pr_body(diagnosis: dict, run_id: str, dag_id: str, alert_id: str) -> str:
    evidence = "\n".join(f"- {line}" for line in (diagnosis.get("evidence") or [])[:10])
    return (
        "**Auto-generated by `auto_fix_pr_handler` based on Astro Investigation Agent diagnosis.**\n\n"
        f"## Summary\n{diagnosis.get('summary', '')}\n\n"
        "## Root cause\n"
        f"- **Cause:** {diagnosis.get('root_cause', '')}\n"
        f"- **Task:** `{diagnosis.get('root_cause_task', '')}`\n"
        f"- **Type:** `{diagnosis.get('root_cause_type', '')}` ({diagnosis.get('transience', '')})\n\n"
        "## Severity & confidence\n"
        f"- Severity: {diagnosis.get('severity', '')} (priority {diagnosis.get('priority', '')})\n"
        f"- Confidence: {diagnosis.get('confidence', 0):.2f} ({diagnosis.get('confidence_justification', '')})\n\n"
        "## Suggested fix (raw from agent)\n"
        f"{diagnosis.get('suggested_fix', '')}\n\n"
        f"## Evidence\n{evidence}\n\n"
        "---\n"
        f"Generated from failed run `{run_id}` in `{dag_id}`.\n"
        f"Alert ID: `{alert_id}`."
    )
