import base64
import os
import re
from urllib.parse import quote

import requests

GITLAB_API = os.environ.get("GITLAB_BASE_URL", "https://gitlab.com/api/v4").rstrip("/")


def gitlab_headers() -> dict[str, str]:
    return {
        "PRIVATE-TOKEN": os.environ["GITLAB_TOKEN"],
    }


def _encode(value: str) -> str:
    return quote(value, safe="")


def find_dag_file_path(project: str, ref: str, dag_id: str, dags_dir: str = "dags") -> str:
    resp = requests.get(
        f"{GITLAB_API}/projects/{_encode(project)}/repository/tree",
        params={"path": dags_dir, "ref": ref},
        headers=gitlab_headers(),
        timeout=15,
    )
    resp.raise_for_status()
    entries = [
        entry
        for entry in resp.json()
        if entry["type"] == "blob" and entry["name"].endswith(".py")
    ]

    exact_name = f"{dag_id}.py"
    for entry in entries:
        if entry["name"] == exact_name:
            return entry["path"]

    for entry in entries:
        if dag_id in get_repo_file(project, ref, entry["path"])["content"]:
            return entry["path"]

    raise RuntimeError(
        f"No file under {dags_dir}/ in {project}@{ref} defines dag_id {dag_id!r}"
    )


def find_open_mr(project: str, label: str) -> dict | None:
    resp = requests.get(
        f"{GITLAB_API}/projects/{_encode(project)}/merge_requests",
        params={"state": "opened", "labels": label},
        headers=gitlab_headers(),
        timeout=15,
    )
    resp.raise_for_status()
    mrs = resp.json()
    return mrs[0] if mrs else None


def get_repo_file(project: str, ref: str, path: str) -> dict[str, str]:
    resp = requests.get(
        f"{GITLAB_API}/projects/{_encode(project)}/repository/files/{_encode(path)}",
        params={"ref": ref},
        headers=gitlab_headers(),
        timeout=15,
    )
    resp.raise_for_status()
    body = resp.json()
    return {"content": base64.b64decode(body["content"]).decode("utf-8")}


def create_branch(project: str, base_branch: str, branch: str) -> None:
    resp = requests.post(
        f"{GITLAB_API}/projects/{_encode(project)}/repository/branches",
        params={"branch": branch, "ref": base_branch},
        headers=gitlab_headers(),
        timeout=15,
    )
    resp.raise_for_status()


def commit_file(project: str, branch: str, path: str, content: str, message: str) -> None:
    resp = requests.post(
        f"{GITLAB_API}/projects/{_encode(project)}/repository/commits",
        headers=gitlab_headers(),
        json={
            "branch": branch,
            "commit_message": message,
            "actions": [
                {
                    "action": "update",
                    "file_path": path,
                    "content": base64.b64encode(content.encode("utf-8")).decode("ascii"),
                    "encoding": "base64",
                }
            ],
        },
        timeout=30,
    )
    resp.raise_for_status()


def ensure_label(project: str, label: str) -> None:
    resp = requests.post(
        f"{GITLAB_API}/projects/{_encode(project)}/labels",
        headers=gitlab_headers(),
        json={"name": label, "color": "0e8a16"},
        timeout=15,
    )
    if resp.status_code >= 500:
        resp.raise_for_status()


def create_merge_request(
    project: str, base_branch: str, branch: str, title: str, body: str, labels: str
) -> dict:
    resp = requests.post(
        f"{GITLAB_API}/projects/{_encode(project)}/merge_requests",
        headers=gitlab_headers(),
        json={
            "source_branch": branch,
            "target_branch": base_branch,
            "title": title,
            "description": body,
            "labels": labels,
        },
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()


def build_branch_name(dag_id: str, run_id: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9]+", "-", run_id).strip("-")[:24]
    return f"auto-fix/{dag_id}/{slug}"


def render_mr_body(diagnosis: dict, run_id: str, dag_id: str, alert_id: str) -> str:
    evidence = "\n".join(f"- {line}" for line in (diagnosis.get("evidence") or [])[:10])
    return (
        "**Auto-generated by the `open_mr` task based on Astro Investigation Agent diagnosis.**\n\n"
        f"## Summary\n{diagnosis.get('summary', '')}\n\n"
        "## Root cause\n"
        f"- **Cause:** {diagnosis.get('root_cause', '')}\n"
        f"- **Task:** `{diagnosis.get('root_cause_task', '')}`\n"
        f"- **Type:** `{diagnosis.get('root_cause_type', '')}` ({diagnosis.get('transience', '')})\n\n"
        "## Severity & confidence\n"
        f"- Severity: {diagnosis.get('severity', '')} (priority {diagnosis.get('priority', '')})\n"
        f"- Confidence: {diagnosis.get('confidence', 0):.2f} ({diagnosis.get('confidence_justification', '')})\n\n"
        "## Suggested fix (raw from agent)\n"
        f"{diagnosis.get('suggested_fix', '')}\n\n"
        f"## Evidence\n{evidence}\n\n"
        "---\n"
        f"Generated from failed run `{run_id}` in `{dag_id}`.\n"
        f"Alert ID: `{alert_id}`."
    )
